/* ========================================================================= */
/* STANDALONE QUANTUM SIMULATION RUNTIME (GENERATED BY ZCC PHASE 0D)        */
/* Zero runtime dependency on ZCC - requires only C99/C11 libc and libm (-lm)*/
/* ========================================================================= */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <string.h>
#include <inttypes.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#ifndef M_SQRT1_2
#define M_SQRT1_2 0.70710678118654752440
#endif

typedef struct {
    double real;
    double imag;
} zcc_complex_t;

static inline zcc_complex_t c_make(double r, double i) { zcc_complex_t c = {r, i}; return c; }
static inline zcc_complex_t c_add(zcc_complex_t a, zcc_complex_t b) { return c_make(a.real + b.real, a.imag + b.imag); }
static inline zcc_complex_t c_sub(zcc_complex_t a, zcc_complex_t b) { return c_make(a.real - b.real, a.imag - b.imag); }
static inline zcc_complex_t c_mul(zcc_complex_t a, zcc_complex_t b) {
    return c_make(a.real * b.real - a.imag * b.imag, a.real * b.imag + a.imag * b.real);
}
static inline zcc_complex_t c_scale(zcc_complex_t a, double s) { return c_make(a.real * s, a.imag * s); }
static inline double c_mag_sq(zcc_complex_t a) { return a.real * a.real + a.imag * a.imag; }
static inline double c_mag(zcc_complex_t a) { return sqrt(c_mag_sq(a)); }
static inline zcc_complex_t c_exp_i(double theta) { return c_make(cos(theta), sin(theta)); }

typedef struct {
    size_t num_qubits;
    size_t num_clbits;
    size_t num_amplitudes;
    zcc_complex_t *amplitudes;
    uint8_t *clbits;
    uint64_t rng_state;
} ZCCQasmState;

static uint64_t zcc_rng_next(ZCCQasmState *s) {
    s->rng_state += 0x9e3779b97f4a7c15ULL;
    uint64_t z = s->rng_state;
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
}

static double zcc_rng_uniform(ZCCQasmState *s) {
    return (double)(zcc_rng_next(s) >> 11) * (1.0 / 9007199254740992.0);
}

static ZCCQasmState *zcc_state_create(size_t num_qubits, size_t num_clbits, uint64_t seed) {
    if (num_qubits > 28) {
        fprintf(stderr, "error: requested qubit count %zu exceeds standalone simulation limit (28)\n", num_qubits);
        return NULL;
    }
    ZCCQasmState *s = (ZCCQasmState *)calloc(1, sizeof(ZCCQasmState));
    if (!s) return NULL;
    s->num_qubits = num_qubits;
    s->num_clbits = num_clbits;
    s->num_amplitudes = (size_t)1 << num_qubits;
    s->amplitudes = (zcc_complex_t *)calloc(s->num_amplitudes, sizeof(zcc_complex_t));
    if (!s->amplitudes) {
        free(s);
        return NULL;
    }
    if (num_clbits > 0) {
        s->clbits = (uint8_t *)calloc(num_clbits, sizeof(uint8_t));
    }
    s->amplitudes[0] = c_make(1.0, 0.0); /* Ground state |0...0> */
    s->rng_state = (seed != 0) ? seed : 0x123456789ABCDEF0ULL;
    return s;
}

static void zcc_state_free(ZCCQasmState *s) {
    if (!s) return;
    if (s->amplitudes) free(s->amplitudes);
    if (s->clbits) free(s->clbits);
    free(s);
}

/* 1-Qubit Unitary Transformation */
static void zcc_apply_1q(ZCCQasmState *s, size_t q, zcc_complex_t u00, zcc_complex_t u01, zcc_complex_t u10, zcc_complex_t u11) {
    size_t stride = (size_t)1 << q;
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i += (stride << 1)) {
        for (size_t j = 0; j < stride; j++) {
            size_t idx0 = i + j;
            size_t idx1 = idx0 + stride;
            zcc_complex_t a0 = s->amplitudes[idx0];
            zcc_complex_t a1 = s->amplitudes[idx1];
            s->amplitudes[idx0] = c_add(c_mul(u00, a0), c_mul(u01, a1));
            s->amplitudes[idx1] = c_add(c_mul(u10, a0), c_mul(u11, a1));
        }
    }
}

/* Controlled 1-Qubit Unitary Transformation */
static void zcc_apply_controlled_1q(ZCCQasmState *s, size_t ctrl, size_t target, zcc_complex_t u00, zcc_complex_t u01, zcc_complex_t u10, zcc_complex_t u11) {
    size_t stride = (size_t)1 << target;
    size_t ctrl_mask = (size_t)1 << ctrl;
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i += (stride << 1)) {
        for (size_t j = 0; j < stride; j++) {
            size_t idx0 = i + j;
            size_t idx1 = idx0 + stride;
            if (idx0 & ctrl_mask) {
                zcc_complex_t a0 = s->amplitudes[idx0];
                zcc_complex_t a1 = s->amplitudes[idx1];
                s->amplitudes[idx0] = c_add(c_mul(u00, a0), c_mul(u01, a1));
                s->amplitudes[idx1] = c_add(c_mul(u10, a0), c_mul(u11, a1));
            }
        }
    }
}

/* Standard 1-Qubit Gates */
static inline void zcc_gate_h(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(M_SQRT1_2, 0.0), c_make(M_SQRT1_2, 0.0),
                       c_make(M_SQRT1_2, 0.0), c_make(-M_SQRT1_2, 0.0));
}
static inline void zcc_gate_x(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(0.0, 0.0), c_make(1.0, 0.0),
                       c_make(1.0, 0.0), c_make(0.0, 0.0));
}
static inline void zcc_gate_y(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(0.0, 0.0), c_make(0.0, -1.0),
                       c_make(0.0, 1.0), c_make(0.0, 0.0));
}
static inline void zcc_gate_z(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(1.0, 0.0), c_make(0.0, 0.0),
                       c_make(0.0, 0.0), c_make(-1.0, 0.0));
}
static inline void zcc_gate_s(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(1.0, 0.0), c_make(0.0, 0.0),
                       c_make(0.0, 0.0), c_make(0.0, 1.0));
}
static inline void zcc_gate_sdg(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(1.0, 0.0), c_make(0.0, 0.0),
                       c_make(0.0, 0.0), c_make(0.0, -1.0));
}
static inline void zcc_gate_t(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(1.0, 0.0), c_make(0.0, 0.0),
                       c_make(0.0, 0.0), c_exp_i(M_PI / 4.0));
}
static inline void zcc_gate_tdg(ZCCQasmState *s, size_t q) {
    zcc_apply_1q(s, q, c_make(1.0, 0.0), c_make(0.0, 0.0),
                       c_make(0.0, 0.0), c_exp_i(-M_PI / 4.0));
}
static inline void zcc_gate_rx(ZCCQasmState *s, size_t q, double theta) {
    double half = theta * 0.5;
    zcc_apply_1q(s, q, c_make(cos(half), 0.0), c_make(0.0, -sin(half)),
                       c_make(0.0, -sin(half)), c_make(cos(half), 0.0));
}
static inline void zcc_gate_ry(ZCCQasmState *s, size_t q, double theta) {
    double half = theta * 0.5;
    zcc_apply_1q(s, q, c_make(cos(half), 0.0), c_make(-sin(half), 0.0),
                       c_make(sin(half), 0.0), c_make(cos(half), 0.0));
}
static inline void zcc_gate_rz(ZCCQasmState *s, size_t q, double theta) {
    double half = theta * 0.5;
    zcc_apply_1q(s, q, c_exp_i(-half), c_make(0.0, 0.0),
                       c_make(0.0, 0.0), c_exp_i(half));
}
static inline void zcc_gate_p(ZCCQasmState *s, size_t q, double lambda) {
    zcc_apply_1q(s, q, c_make(1.0, 0.0), c_make(0.0, 0.0),
                       c_make(0.0, 0.0), c_exp_i(lambda));
}
static inline void zcc_gate_u3(ZCCQasmState *s, size_t q, double theta, double phi, double lambda) {
    double half = theta * 0.5;
    double c_val = cos(half);
    double s_val = sin(half);
    zcc_complex_t u00 = c_make(c_val, 0.0);
    zcc_complex_t u01 = c_scale(c_exp_i(lambda), -s_val);
    zcc_complex_t u10 = c_scale(c_exp_i(phi), s_val);
    zcc_complex_t u11 = c_scale(c_exp_i(phi + lambda), c_val);
    zcc_apply_1q(s, q, u00, u01, u10, u11);
}
static inline void zcc_gate_u2(ZCCQasmState *s, size_t q, double phi, double lambda) {
    zcc_complex_t u00 = c_make(M_SQRT1_2, 0.0);
    zcc_complex_t u01 = c_scale(c_exp_i(lambda), -M_SQRT1_2);
    zcc_complex_t u10 = c_scale(c_exp_i(phi), M_SQRT1_2);
    zcc_complex_t u11 = c_scale(c_exp_i(phi + lambda), M_SQRT1_2);
    zcc_apply_1q(s, q, u00, u01, u10, u11);
}
static inline void zcc_gate_u1(ZCCQasmState *s, size_t q, double lambda) {
    zcc_gate_p(s, q, lambda);
}

/* 2-Qubit Gates */
static inline void zcc_gate_cx(ZCCQasmState *s, size_t ctrl, size_t target) {
    zcc_apply_controlled_1q(s, ctrl, target, c_make(0.0, 0.0), c_make(1.0, 0.0),
                                             c_make(1.0, 0.0), c_make(0.0, 0.0));
}
static inline void zcc_gate_cy(ZCCQasmState *s, size_t ctrl, size_t target) {
    zcc_apply_controlled_1q(s, ctrl, target, c_make(0.0, 0.0), c_make(0.0, -1.0),
                                             c_make(0.0, 1.0), c_make(0.0, 0.0));
}
static inline void zcc_gate_cz(ZCCQasmState *s, size_t q0, size_t q1) {
    zcc_apply_controlled_1q(s, q0, q1, c_make(1.0, 0.0), c_make(0.0, 0.0),
                                       c_make(0.0, 0.0), c_make(-1.0, 0.0));
}
static inline void zcc_gate_ch(ZCCQasmState *s, size_t ctrl, size_t target) {
    zcc_apply_controlled_1q(s, ctrl, target, c_make(M_SQRT1_2, 0.0), c_make(M_SQRT1_2, 0.0),
                                             c_make(M_SQRT1_2, 0.0), c_make(-M_SQRT1_2, 0.0));
}
static void zcc_gate_swap(ZCCQasmState *s, size_t q0, size_t q1) {
    size_t mask0 = (size_t)1 << q0;
    size_t mask1 = (size_t)1 << q1;
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i++) {
        if ((i & mask0) && !(i & mask1)) {
            size_t j = (i & ~mask0) | mask1;
            zcc_complex_t tmp = s->amplitudes[i];
            s->amplitudes[i] = s->amplitudes[j];
            s->amplitudes[j] = tmp;
        }
    }
}
static void zcc_gate_iswap(ZCCQasmState *s, size_t q0, size_t q1) {
    size_t mask0 = (size_t)1 << q0;
    size_t mask1 = (size_t)1 << q1;
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i++) {
        if ((i & mask0) && !(i & mask1)) {
            size_t j = (i & ~mask0) | mask1;
            zcc_complex_t ai = s->amplitudes[i];
            zcc_complex_t aj = s->amplitudes[j];
            s->amplitudes[i] = c_make(-aj.imag, aj.real);
            s->amplitudes[j] = c_make(-ai.imag, ai.real);
        }
    }
}
static inline void zcc_gate_crx(ZCCQasmState *s, size_t ctrl, size_t target, double theta) {
    double half = theta * 0.5;
    zcc_apply_controlled_1q(s, ctrl, target, c_make(cos(half), 0.0), c_make(0.0, -sin(half)),
                                             c_make(0.0, -sin(half)), c_make(cos(half), 0.0));
}
static inline void zcc_gate_cry(ZCCQasmState *s, size_t ctrl, size_t target, double theta) {
    double half = theta * 0.5;
    zcc_apply_controlled_1q(s, ctrl, target, c_make(cos(half), 0.0), c_make(-sin(half), 0.0),
                                             c_make(sin(half), 0.0), c_make(cos(half), 0.0));
}
static inline void zcc_gate_crz(ZCCQasmState *s, size_t ctrl, size_t target, double theta) {
    double half = theta * 0.5;
    zcc_apply_controlled_1q(s, ctrl, target, c_exp_i(-half), c_make(0.0, 0.0),
                                             c_make(0.0, 0.0), c_exp_i(half));
}
static inline void zcc_gate_cu1(ZCCQasmState *s, size_t ctrl, size_t target, double lambda) {
    zcc_apply_controlled_1q(s, ctrl, target, c_make(1.0, 0.0), c_make(0.0, 0.0),
                                             c_make(0.0, 0.0), c_exp_i(lambda));
}
static inline void zcc_gate_cu3(ZCCQasmState *s, size_t ctrl, size_t target, double theta, double phi, double lambda) {
    double half = theta * 0.5;
    double c_val = cos(half);
    double s_val = sin(half);
    zcc_complex_t u00 = c_make(c_val, 0.0);
    zcc_complex_t u01 = c_scale(c_exp_i(lambda), -s_val);
    zcc_complex_t u10 = c_scale(c_exp_i(phi), s_val);
    zcc_complex_t u11 = c_scale(c_exp_i(phi + lambda), c_val);
    zcc_apply_controlled_1q(s, ctrl, target, u00, u01, u10, u11);
}
static void zcc_gate_rzz(ZCCQasmState *s, size_t q0, size_t q1, double theta) {
    double half = theta * 0.5;
    zcc_complex_t p_neg = c_exp_i(-half);
    zcc_complex_t p_pos = c_exp_i(half);
    size_t mask0 = (size_t)1 << q0;
    size_t mask1 = (size_t)1 << q1;
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i++) {
        int b0 = (i & mask0) ? 1 : 0;
        int b1 = (i & mask1) ? 1 : 0;
        s->amplitudes[i] = c_mul(s->amplitudes[i], (b0 == b1) ? p_neg : p_pos);
    }
}

/* 3-Qubit Gates */
static void zcc_gate_ccx(ZCCQasmState *s, size_t c0, size_t c1, size_t target) {
    size_t stride = (size_t)1 << target;
    size_t ctrl_mask = ((size_t)1 << c0) | ((size_t)1 << c1);
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i += (stride << 1)) {
        for (size_t j = 0; j < stride; j++) {
            size_t idx0 = i + j;
            size_t idx1 = idx0 + stride;
            if ((idx0 & ctrl_mask) == ctrl_mask) {
                zcc_complex_t tmp = s->amplitudes[idx0];
                s->amplitudes[idx0] = s->amplitudes[idx1];
                s->amplitudes[idx1] = tmp;
            }
        }
    }
}
static void zcc_gate_cswap(ZCCQasmState *s, size_t ctrl, size_t a, size_t b) {
    size_t ctrl_mask = (size_t)1 << ctrl;
    size_t mask_a = (size_t)1 << a;
    size_t mask_b = (size_t)1 << b;
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i++) {
        if ((i & ctrl_mask) && (i & mask_a) && !(i & mask_b)) {
            size_t j = (i & ~mask_a) | mask_b;
            zcc_complex_t tmp = s->amplitudes[i];
            s->amplitudes[i] = s->amplitudes[j];
            s->amplitudes[j] = tmp;
        }
    }
}

/* Projective Measurement */
static int zcc_op_measure(ZCCQasmState *s, size_t q, size_t clbit_idx) {
    size_t mask = (size_t)1 << q;
    double p1 = 0.0;
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i++) {
        if (i & mask) p1 += c_mag_sq(s->amplitudes[i]);
    }
    double r = zcc_rng_uniform(s);
    int outcome = (r >= (1.0 - p1)) ? 1 : 0;
    double norm_factor = outcome ? sqrt(p1) : sqrt(1.0 - p1);
    if (norm_factor < 1e-15) norm_factor = 1e-15;
    double inv_norm = 1.0 / norm_factor;
    for (size_t i = 0; i < num_amps; i++) {
        int bit = (i & mask) ? 1 : 0;
        if (bit == outcome) {
            s->amplitudes[i] = c_scale(s->amplitudes[i], inv_norm);
        } else {
            s->amplitudes[i] = c_make(0.0, 0.0);
        }
    }
    if (s->clbits && clbit_idx < s->num_clbits) {
        s->clbits[clbit_idx] = (uint8_t)outcome;
    }
    return outcome;
}

/* Qubit Reset Operator */
static void zcc_op_reset(ZCCQasmState *s, size_t q) {
    int outcome = zcc_op_measure(s, q, (size_t)-1);
    if (outcome == 1) {
        zcc_gate_x(s, q);
    }
}

/* Reduced 1-Qubit Von Neumann Entropy */
static double zcc_entropy_1q(const ZCCQasmState *s, size_t q) {
    size_t mask = (size_t)1 << q;
    double rho00 = 0.0, rho11 = 0.0;
    zcc_complex_t rho01 = c_make(0.0, 0.0);
    size_t num_amps = s->num_amplitudes;
    for (size_t i = 0; i < num_amps; i++) {
        if ((i & mask) == 0) {
            size_t i1 = i | mask;
            rho00 += c_mag_sq(s->amplitudes[i]);
            rho11 += c_mag_sq(s->amplitudes[i1]);
            rho01 = c_add(rho01, c_mul(s->amplitudes[i], c_make(s->amplitudes[i1].real, -s->amplitudes[i1].imag)));
        }
    }
    double disc = sqrt((rho00 - rho11) * (rho00 - rho11) + 4.0 * c_mag_sq(rho01));
    double l0 = 0.5 * (rho00 + rho11 + disc);
    double l1 = 0.5 * (rho00 + rho11 - disc);
    double ent = 0.0;
    if (l0 > 1e-15) ent -= l0 * (log(l0) / log(2.0));
    if (l1 > 1e-15) ent -= l1 * (log(l1) / log(2.0));
    return (ent < 0.0) ? 0.0 : ent;
}

/* Statevector Formatting */
static void zcc_dump_state(const ZCCQasmState *s, double threshold) {
    size_t num_amps = s->num_amplitudes;
    size_t n = s->num_qubits;
    for (size_t i = 0; i < num_amps; i++) {
        double p = c_mag_sq(s->amplitudes[i]);
        if (p >= threshold) {
            printf("|");
            for (int bit = (int)n - 1; bit >= 0; bit--) {
                printf("%c", (i & ((size_t)1 << bit)) ? '1' : '0');
            }
            printf(">: %+.8f %+.8fi (prob: %.6f)\n", s->amplitudes[i].real, s->amplitudes[i].imag, p);
        }
    }
}

/* Circuit Execution Function */
void run_quantum_circuit(ZCCQasmState *state) {
    zcc_gate_x(state, 4);
    zcc_gate_h(state, 0);
    zcc_gate_s(state, 0);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
    zcc_gate_h(state, 0);
    zcc_gate_h(state, 1);
    zcc_gate_cu1(state, 2, 1, 1.5707963300000001);
    zcc_gate_cu1(state, 3, 1, 0.78539815999999996);
    zcc_gate_cu1(state, 4, 1, 0.39269907999999998);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 3, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 4, 2, 0.78539815999999996);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 3, 1.5707963300000001);
    zcc_gate_h(state, 4);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, 3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, 1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, 0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, 0.39269907999999998);
    zcc_gate_x(state, 0);
    zcc_gate_cu1(state, 0, 1, -3.1415926500000002);
    zcc_gate_cu1(state, 0, 2, -1.5707963300000001);
    zcc_gate_cu1(state, 0, 3, -0.78539815999999996);
    zcc_gate_cu1(state, 0, 4, -0.39269907999999998);
    zcc_gate_swap(state, 1, 4);
    zcc_gate_swap(state, 2, 3);
    zcc_gate_h(state, 4);
    zcc_gate_cu1(state, 4, 3, -1.5707963300000001);
    zcc_gate_h(state, 3);
    zcc_gate_cu1(state, 4, 2, -0.78539815999999996);
    zcc_gate_cu1(state, 3, 2, -1.5707963300000001);
    zcc_gate_h(state, 2);
    zcc_gate_cu1(state, 4, 1, -0.39269907999999998);
    zcc_gate_cu1(state, 3, 1, -0.78539815999999996);
    zcc_gate_cu1(state, 2, 1, -1.5707963300000001);
    zcc_gate_h(state, 1);
}

int main(int argc, char **argv) {
    uint64_t seed = 0x123456789ABCDEF0ULL;
    double threshold = 1e-6;
    int dump_state = 1;
    int show_entropy = 0;

    for (int i = 1; i < argc; i++) {
        if (strncmp(argv[i], "--seed=", 7) == 0) {
            seed = strtoull(argv[i] + 7, NULL, 0);
        } else if (strncmp(argv[i], "--threshold=", 12) == 0) {
            threshold = atof(argv[i] + 12);
        } else if (strcmp(argv[i], "--entropy") == 0) {
            show_entropy = 1;
        } else if (strcmp(argv[i], "--no-dump") == 0) {
            dump_state = 0;
        }
    }

    size_t num_qubits = 5;
    size_t num_clbits = 5;
    threshold = 9.9999999999999995e-07;
    ZCCQasmState *state = zcc_state_create(num_qubits, num_clbits, seed);
    if (!state) {
        fprintf(stderr, "error: statevector allocation failed\n");
        return 1;
    }

    run_quantum_circuit(state);

    if (dump_state) {
        zcc_dump_state(state, threshold);
    }

    if (show_entropy && num_qubits > 1) {
        for (size_t q = 0; q < num_qubits; q++) {
            printf("S(q%zu) = %.6f bits\n", q, zcc_entropy_1q(state, q));
        }
    }

    zcc_state_free(state);
    return 0;
}
